package:
  name: plsmd
  version: "v1.0"

source:
  git_url: https://github.com/Genomics-and-Metagenomics-Unit-57357/plsMD/

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    cp plsmd $PREFIX/bin/
    cp preprocessing.sh $PREFIX/bin/
    cp plsMD.py $PREFIX/bin/
    cp annotation.sh $PREFIX/bin/
    cp phylogenetics.sh $PREFIX/bin/
    chmod +x $PREFIX/bin/plsmd
    chmod +x $PREFIX/bin/plsMD_preprocessing.sh
    chmod +x $PREFIX/bin/plsMD_processing.py
    chmod +x $PREFIX/bin/plsMD_annotation.sh
    chmod +x $PREFIX/bin/plsMD_phylogenetics.sh

requirements:
  run:
    - python=3.8
    - bioconda::abricate
    - bioconda::blast
    - bioconda::seqtk
    - bioconda::mafft
    - bioconda::iqtree
    - bioconda::biopython

about:
  home: "https://github.com/Genomics-and-Metagenomics-Unit-57357/plsMD/"
  summary: "A bioinformatics tool for plasmid reconstruction from short-read assemblies"
  license: MIT


