package:
  name: plsmd
  version: "1.0"

source:
  url: https://github.com/Genomics-and-Metagenomics-Unit-57357/plsMD/archive/refs/tags/v1.0.tar.gz
  sha256: 4c1b91daadcd05b2fdef2eb3cf9194e7aa37cc5e78b1172e6bc3d012090e

build:
  number: 0
  noarch: generic
  script: |
    mkdir -p $PREFIX/bin
    cp plsmd $PREFIX/bin/
    cp preprocessing.sh $PREFIX/bin/
    cp plsMD.py $PREFIX/bin/
    cp annotation.sh $PREFIX/bin/
    cp phylogenetics.sh $PREFIX/bin/
    chmod +x $PREFIX/bin/plsmd
    chmod +x $PREFIX/bin/plsMD_preprocessing.sh
    chmod +x $PREFIX/bin/plsMD_processing.py
    chmod +x $PREFIX/bin/plsMD_annotation.sh
    chmod +x $PREFIX/bin/plsMD_phylogenetics.sh

requirements:
  run:
    - python =3.8
    - bioconda::abricate
    - bioconda::blast
    - bioconda::seqtk
    - bioconda::mafft
    - bioconda::iqtree
    - bioconda::biopython

test:
  commands:
    - plsmd --help  

about:
  home: "https://github.com/Genomics-and-Metagenomics-Unit-57357/plsMD/"
  summary: "A bioinformatics tool for plasmid reconstruction from short-read assemblies"
  license: MIT


